name: Daily Playwright Auto Check-In

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 2 * * *" # daily at 2 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python (with pip caching)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: req.txt


      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: pip install --upgrade -r req.txt
#5. playwirht browser
      - name: Setup Playwright browsers cache
        id: down-playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('req.txt') }}

      - name: Install Playwright browsers if not cached
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: python -m playwright install --with-deps chromium firefox webkit


      # 6. Run your script
      - name: Run Auto Check-In Script
        run: python auto4.py
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}

      # 7. Upload logs for debugging
      - name: Upload script logs
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: script_output.log
