name: Daily Playwright Automation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-playwright-script:
    runs-on: ubuntu-latest

    # Use Playwright official Docker image (includes browsers & Python)
    container:
      image: mcr.microsoft.com/playwright/python:v1.46.0-focal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('req.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run Playwright script
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
        run: python auto4.py

      - name: Commit log file
        uses: EndBug/add-and-commit@v9
        with:
          add: "script_output.log"
          message: "Update script log"

      - name: Commit other changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
