name: run-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

jobs:
  run-automation:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 3. Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 5. Install Playwright browsers (only if not cached)
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: python -m playwright install --with-deps chromium

      # 6. Run automation script
      - name: Run automation script
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
        run: python main.py > output.log 2>&1

      # 7. Upload log file (latest version)
      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: automation-log
          path: output.log
